In [1]:
import numpy as np

from utils import GamblerProblemModel

In [2]:
p = GamblerProblemModel(goal=10, success_probability=0.4)
p.n_states, p.n_nonterminal_states, p.n_actions

(11, 9, 5)

In [3]:
p.immediate_rewards

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [4]:
tps = p.define_transition_probability_matrices()

first = np.matvec(tps, p.immediate_rewards)
np.argmax(first, axis=0)

array([0, 0, 0, 0, 0, 4, 3, 2, 1, 0, 0])

In [5]:
np.max(first, axis=0)

array([0. , 0. , 0. , 0. , 0. , 0.4, 0.4, 0.4, 0.4, 0.4, 0. ])

In [6]:
first

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.4, 0. , 0. , 0. , 0. , 0. ]])

In [7]:
v = np.zeros(11)
for i in range(10):
    comp = np.matvec(tps, v + p.immediate_rewards)
    print(np.argmax(comp, axis=0))
    v = np.max(comp, axis=0)
    print(v)
    print()

[0 0 0 0 0 4 3 2 1 0 0]
[0.  0.  0.  0.  0.  0.4 0.4 0.4 0.4 0.4 0. ]

[0 0 0 1 0 4 0 0 1 0 0]
[0.   0.   0.   0.16 0.16 0.4  0.4  0.4  0.64 0.64 0.  ]

[0 0 0 1 0 4 0 2 1 0 0]
[0.    0.    0.064 0.16  0.256 0.4   0.4   0.496 0.64  0.784 0.   ]

[0 0 1 1 0 4 0 1 1 0 0]
[0.     0.0256 0.1024 0.16   0.256  0.4    0.4384 0.5536 0.64   0.784
 0.    ]

[0 0 1 1 0 4 0 1 1 0 0]
[0.      0.04096 0.1024  0.17536 0.256   0.4     0.46144 0.5536  0.66304
 0.784   0.     ]

[0 0 1 1 0 4 0 1 1 0 0]
[0.       0.04096  0.1024   0.184576 0.265216 0.4      0.46144  0.5536
 0.676864 0.797824 0.      ]

[0 0 1 1 3 4 0 1 1 0 0]
[0.        0.04096   0.1060864 0.184576  0.2707456 0.4       0.46144
 0.5591296 0.676864  0.8061184 0.       ]

[0 0 1 1 3 4 0 1 1 0 0]
[0.         0.04243456 0.10829824 0.184576   0.2707456  0.4
 0.46365184 0.56244736 0.676864   0.8061184  0.        ]

[0 0 1 1 3 4 0 1 1 0 0]
[0.         0.0433193  0.10829824 0.18546074 0.2707456  0.4
 0.46497894 0.56244736 0.6781911  0.8061184  0.